services:
    # Laravel Telebot Application
    app:
        build: .
        container_name: telebot-app
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./storage:/var/www/html/storage
            - ./database/database.sqlite:/var/www/html/database/database.sqlite
        env_file:
            - .env
        networks:
            - proxy-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s

    # Nginx Proxy Manager
    npm:
        image: "jc21/nginx-proxy-manager:latest"
        container_name: nginx-proxy-manager
        restart: unless-stopped
        ports:
            - "80:80" # HTTP
            - "443:443" # HTTPS
            - "81:81" # Admin panel
        volumes:
            - npm-data:/data
            - npm-letsencrypt:/etc/letsencrypt
        networks:
            - proxy-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:81/"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s

networks:
    proxy-network:
        driver: bridge

volumes:
    npm-data:
    npm-letsencrypt:
